// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-srv.proto

package user_srv

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_main  Type = 0
	Type_extra Type = 1
	Type_meta  Type = 2
)

var Type_name = map[int32]string{
	0: "main",
	1: "extra",
	2: "meta",
}

var Type_value = map[string]int32{
	"main":  0,
	"extra": 1,
	"meta":  2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7318836fc8ef5002, []int{0}
}

type UserMain struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Message              string   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMain) Reset()         { *m = UserMain{} }
func (m *UserMain) String() string { return proto.CompactTextString(m) }
func (*UserMain) ProtoMessage()    {}
func (*UserMain) Descriptor() ([]byte, []int) {
	return fileDescriptor_7318836fc8ef5002, []int{0}
}

func (m *UserMain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMain.Unmarshal(m, b)
}
func (m *UserMain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMain.Marshal(b, m, deterministic)
}
func (m *UserMain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMain.Merge(m, src)
}
func (m *UserMain) XXX_Size() int {
	return xxx_messageInfo_UserMain.Size(m)
}
func (m *UserMain) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMain.DiscardUnknown(m)
}

var xxx_messageInfo_UserMain proto.InternalMessageInfo

func (m *UserMain) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserMain) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserMain) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserMain) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserMain) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UserExtra struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Gender               string   `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	BirthdayUTC          int64    `protobuf:"varint,5,opt,name=birthdayUTC,proto3" json:"birthdayUTC,omitempty"`
	Message              string   `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserExtra) Reset()         { *m = UserExtra{} }
func (m *UserExtra) String() string { return proto.CompactTextString(m) }
func (*UserExtra) ProtoMessage()    {}
func (*UserExtra) Descriptor() ([]byte, []int) {
	return fileDescriptor_7318836fc8ef5002, []int{1}
}

func (m *UserExtra) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserExtra.Unmarshal(m, b)
}
func (m *UserExtra) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserExtra.Marshal(b, m, deterministic)
}
func (m *UserExtra) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserExtra.Merge(m, src)
}
func (m *UserExtra) XXX_Size() int {
	return xxx_messageInfo_UserExtra.Size(m)
}
func (m *UserExtra) XXX_DiscardUnknown() {
	xxx_messageInfo_UserExtra.DiscardUnknown(m)
}

var xxx_messageInfo_UserExtra proto.InternalMessageInfo

func (m *UserExtra) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserExtra) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserExtra) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserExtra) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UserExtra) GetBirthdayUTC() int64 {
	if m != nil {
		return m.BirthdayUTC
	}
	return 0
}

func (m *UserExtra) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UserMeta struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	AccountStatus        string   `protobuf:"bytes,2,opt,name=accountStatus,proto3" json:"accountStatus,omitempty"`
	AccountCreationUTC   int64    `protobuf:"varint,3,opt,name=accountCreationUTC,proto3" json:"accountCreationUTC,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMeta) Reset()         { *m = UserMeta{} }
func (m *UserMeta) String() string { return proto.CompactTextString(m) }
func (*UserMeta) ProtoMessage()    {}
func (*UserMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_7318836fc8ef5002, []int{2}
}

func (m *UserMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMeta.Unmarshal(m, b)
}
func (m *UserMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMeta.Marshal(b, m, deterministic)
}
func (m *UserMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMeta.Merge(m, src)
}
func (m *UserMeta) XXX_Size() int {
	return xxx_messageInfo_UserMeta.Size(m)
}
func (m *UserMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMeta.DiscardUnknown(m)
}

var xxx_messageInfo_UserMeta proto.InternalMessageInfo

func (m *UserMeta) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserMeta) GetAccountStatus() string {
	if m != nil {
		return m.AccountStatus
	}
	return ""
}

func (m *UserMeta) GetAccountCreationUTC() int64 {
	if m != nil {
		return m.AccountCreationUTC
	}
	return 0
}

// Add Function
type AddRequest struct {
	MainData             *UserMain  `protobuf:"bytes,1,opt,name=mainData,proto3" json:"mainData,omitempty"`
	ExtraData            *UserExtra `protobuf:"bytes,2,opt,name=extraData,proto3" json:"extraData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7318836fc8ef5002, []int{3}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetMainData() *UserMain {
	if m != nil {
		return m.MainData
	}
	return nil
}

func (m *AddRequest) GetExtraData() *UserExtra {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

type AddResponse struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7318836fc8ef5002, []int{4}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *AddResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Get Function
type GetRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Type                 Type     `protobuf:"varint,4,opt,name=type,proto3,enum=Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7318836fc8ef5002, []int{5}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetRequest) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_main
}

type GetResponse struct {
	Main                 *UserMain  `protobuf:"bytes,1,opt,name=main,proto3" json:"main,omitempty"`
	Extra                *UserExtra `protobuf:"bytes,2,opt,name=extra,proto3" json:"extra,omitempty"`
	Meta                 *UserMeta  `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7318836fc8ef5002, []int{6}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetMain() *UserMain {
	if m != nil {
		return m.Main
	}
	return nil
}

func (m *GetResponse) GetExtra() *UserExtra {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *GetResponse) GetMeta() *UserMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

// Auth Function
type AuthRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7318836fc8ef5002, []int{7}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7318836fc8ef5002, []int{8}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *AuthResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AuthResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

// Update function
type UpdateRequest struct {
	UserID               string     `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Main                 *UserMain  `protobuf:"bytes,2,opt,name=main,proto3" json:"main,omitempty"`
	Extra                *UserExtra `protobuf:"bytes,3,opt,name=extra,proto3" json:"extra,omitempty"`
	Type                 Type       `protobuf:"varint,4,opt,name=type,proto3,enum=Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7318836fc8ef5002, []int{9}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateRequest) GetMain() *UserMain {
	if m != nil {
		return m.Main
	}
	return nil
}

func (m *UpdateRequest) GetExtra() *UserExtra {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *UpdateRequest) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_main
}

type UpdateResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7318836fc8ef5002, []int{10}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Activate Function
type ActivateRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateRequest) Reset()         { *m = ActivateRequest{} }
func (m *ActivateRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateRequest) ProtoMessage()    {}
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7318836fc8ef5002, []int{11}
}

func (m *ActivateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateRequest.Unmarshal(m, b)
}
func (m *ActivateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateRequest.Marshal(b, m, deterministic)
}
func (m *ActivateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateRequest.Merge(m, src)
}
func (m *ActivateRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateRequest.Size(m)
}
func (m *ActivateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateRequest proto.InternalMessageInfo

func (m *ActivateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ActivateResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateResponse) Reset()         { *m = ActivateResponse{} }
func (m *ActivateResponse) String() string { return proto.CompactTextString(m) }
func (*ActivateResponse) ProtoMessage()    {}
func (*ActivateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7318836fc8ef5002, []int{12}
}

func (m *ActivateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateResponse.Unmarshal(m, b)
}
func (m *ActivateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateResponse.Marshal(b, m, deterministic)
}
func (m *ActivateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateResponse.Merge(m, src)
}
func (m *ActivateResponse) XXX_Size() int {
	return xxx_messageInfo_ActivateResponse.Size(m)
}
func (m *ActivateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateResponse proto.InternalMessageInfo

func (m *ActivateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("Type", Type_name, Type_value)
	proto.RegisterType((*UserMain)(nil), "UserMain")
	proto.RegisterType((*UserExtra)(nil), "UserExtra")
	proto.RegisterType((*UserMeta)(nil), "UserMeta")
	proto.RegisterType((*AddRequest)(nil), "AddRequest")
	proto.RegisterType((*AddResponse)(nil), "AddResponse")
	proto.RegisterType((*GetRequest)(nil), "GetRequest")
	proto.RegisterType((*GetResponse)(nil), "GetResponse")
	proto.RegisterType((*AuthRequest)(nil), "AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "AuthResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*ActivateRequest)(nil), "ActivateRequest")
	proto.RegisterType((*ActivateResponse)(nil), "ActivateResponse")
}

func init() { proto.RegisterFile("user-srv.proto", fileDescriptor_7318836fc8ef5002) }

var fileDescriptor_7318836fc8ef5002 = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xc7, 0xfd, 0x27, 0xce, 0xcf, 0x1e, 0xb7, 0x69, 0x7e, 0xab, 0x0a, 0x19, 0x0b, 0x44, 0xb5,
	0x22, 0xa2, 0x2a, 0xb0, 0x12, 0xe1, 0x01, 0x50, 0xd4, 0xa2, 0x8a, 0x03, 0x1c, 0x4c, 0xc3, 0x05,
	0x71, 0xd8, 0xc6, 0x4b, 0x6b, 0x29, 0xb1, 0x5d, 0xef, 0x26, 0x34, 0x67, 0x6e, 0xbc, 0x0d, 0xcf,
	0xc2, 0x0b, 0xa1, 0x5d, 0xff, 0x5b, 0x97, 0x9a, 0x5c, 0xb8, 0x65, 0x66, 0xd6, 0xb3, 0xdf, 0xef,
	0x67, 0x76, 0x02, 0xa3, 0x35, 0x67, 0xc5, 0x4b, 0x5e, 0x6c, 0x48, 0x5e, 0x64, 0x22, 0xc3, 0x3f,
	0x4c, 0x70, 0xe7, 0x9c, 0x15, 0xef, 0x69, 0x92, 0xa2, 0x07, 0x30, 0x94, 0xe5, 0x77, 0x67, 0x81,
	0x79, 0x64, 0x1e, 0x7b, 0x51, 0x15, 0xa1, 0x10, 0x5c, 0xf9, 0x2b, 0xa5, 0x2b, 0x16, 0x58, 0xaa,
	0xd2, 0xc4, 0xe8, 0x10, 0x1c, 0xb6, 0xa2, 0xc9, 0x32, 0xb0, 0x55, 0xa1, 0x0c, 0xe4, 0x17, 0x39,
	0xe5, 0xfc, 0x5b, 0x56, 0xc4, 0xc1, 0xa0, 0xfc, 0xa2, 0x8e, 0x51, 0x00, 0xff, 0xad, 0x18, 0xe7,
	0xf4, 0x8a, 0x05, 0x8e, 0x2a, 0xd5, 0x21, 0xfe, 0x69, 0x82, 0x27, 0xc5, 0xbc, 0xbd, 0x15, 0x05,
	0xed, 0x55, 0xf3, 0x08, 0xbc, 0xaf, 0x49, 0xc1, 0xc5, 0x87, 0x56, 0x4e, 0x9b, 0x90, 0x37, 0x2f,
	0x69, 0x55, 0x2c, 0x25, 0x35, 0xb1, 0xec, 0x78, 0xc5, 0xd2, 0x98, 0x15, 0x95, 0xa6, 0x2a, 0x42,
	0x47, 0xe0, 0x5f, 0x26, 0x85, 0xb8, 0x8e, 0xe9, 0x76, 0x7e, 0x71, 0xaa, 0x54, 0xd9, 0x91, 0x9e,
	0xd2, 0x35, 0x0f, 0xbb, 0x9a, 0x6f, 0x2b, 0x7e, 0x4c, 0xf4, 0x2b, 0x7e, 0x0a, 0xfb, 0x74, 0xb1,
	0xc8, 0xd6, 0xa9, 0xf8, 0x28, 0xa8, 0x58, 0xf3, 0x4a, 0x75, 0x37, 0x89, 0x08, 0xa0, 0x2a, 0x71,
	0x5a, 0x30, 0x2a, 0x92, 0x2c, 0x95, 0x62, 0x6c, 0x25, 0xe6, 0x9e, 0x0a, 0xfe, 0x02, 0x30, 0x8b,
	0xe3, 0x88, 0xdd, 0xac, 0x19, 0x17, 0x68, 0x02, 0xee, 0x8a, 0x26, 0xe9, 0x19, 0x15, 0x54, 0xdd,
	0xee, 0x4f, 0x3d, 0x52, 0x0f, 0x36, 0x6a, 0x4a, 0xe8, 0x18, 0x3c, 0x26, 0xe9, 0xaa, 0x73, 0x96,
	0x3a, 0x07, 0xa4, 0x61, 0x1e, 0xb5, 0x45, 0xfc, 0x06, 0x7c, 0xd5, 0x9e, 0xe7, 0x59, 0xca, 0x59,
	0xaf, 0x37, 0x8d, 0x8c, 0xd5, 0x25, 0x73, 0x03, 0x70, 0xce, 0x44, 0xad, 0xef, 0xdf, 0xbd, 0xad,
	0x87, 0x30, 0x10, 0xdb, 0x9c, 0xa9, 0x19, 0x8e, 0xa6, 0x0e, 0xb9, 0xd8, 0xe6, 0x2c, 0x52, 0x29,
	0xbc, 0x02, 0x5f, 0x5d, 0x59, 0x69, 0x7e, 0x0c, 0x03, 0x69, 0xfc, 0x4f, 0x1e, 0x2a, 0x8d, 0x8e,
	0xc0, 0x51, 0x76, 0xef, 0xe1, 0x50, 0x16, 0x54, 0x03, 0x26, 0xa8, 0xba, 0xbf, 0x69, 0xc0, 0x04,
	0x8d, 0x54, 0x1a, 0x7f, 0x06, 0x7f, 0xb6, 0x16, 0xd7, 0xb5, 0x45, 0xdd, 0x8a, 0xd9, 0x67, 0xc5,
	0xea, 0x5b, 0x13, 0xbb, 0xbb, 0x26, 0xf8, 0x13, 0xec, 0x95, 0xcd, 0x2b, 0x33, 0x87, 0xe0, 0x6c,
	0xe8, 0x32, 0x89, 0x55, 0x6b, 0x37, 0x2a, 0x83, 0x7e, 0xfc, 0x1a, 0x70, 0x5b, 0x07, 0x8e, 0xbf,
	0x9b, 0xb0, 0x3f, 0xcf, 0x63, 0x2a, 0xd8, 0xae, 0xd1, 0xd4, 0xf8, 0xac, 0x1d, 0xf8, 0xec, 0x3e,
	0x7c, 0x7f, 0x99, 0xd4, 0x09, 0x8c, 0x6a, 0x11, 0x95, 0x3f, 0xcd, 0x89, 0xd9, 0x7d, 0x48, 0xcf,
	0xe0, 0x60, 0xb6, 0x10, 0xc9, 0x46, 0x93, 0xdc, 0xe0, 0x34, 0x35, 0x9c, 0xf8, 0x05, 0x8c, 0xdb,
	0x83, 0xbb, 0xda, 0x9e, 0x4c, 0x60, 0x20, 0x05, 0x21, 0xb7, 0xb4, 0x39, 0x36, 0x90, 0x57, 0x39,
	0x1a, 0x9b, 0x2a, 0xc9, 0x04, 0x1d, 0x5b, 0xd3, 0x5f, 0x26, 0x38, 0xd2, 0x19, 0x47, 0x18, 0xec,
	0x59, 0x1c, 0x23, 0x9f, 0xb4, 0x6b, 0x17, 0xee, 0x11, 0x6d, 0x49, 0xb0, 0x81, 0x9e, 0x80, 0x7d,
	0xce, 0x04, 0xf2, 0x49, 0xfb, 0xf4, 0xc3, 0x96, 0x1c, 0x36, 0xd0, 0x04, 0x06, 0x72, 0xac, 0x68,
	0x8f, 0x68, 0x4f, 0x27, 0xdc, 0x27, 0xfa, 0xac, 0xb1, 0x81, 0x9e, 0xc3, 0xb0, 0xe4, 0x83, 0x46,
	0xa4, 0x33, 0xad, 0xf0, 0x80, 0x74, 0xc1, 0x61, 0x03, 0xbd, 0x02, 0xb7, 0xf6, 0x8d, 0xc6, 0xe4,
	0x0e, 0xab, 0xf0, 0x7f, 0x72, 0x17, 0x0a, 0x36, 0x2e, 0x87, 0xea, 0xef, 0xff, 0xf5, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xa3, 0xee, 0x98, 0x7b, 0x10, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*UserMain, error)
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/Users/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*UserMain, error) {
	out := new(UserMain)
	err := c.cc.Invoke(ctx, "/Users/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/Users/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/Users/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error) {
	out := new(ActivateResponse)
	err := c.cc.Invoke(ctx, "/Users/Activate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
	Get(context.Context, *GetRequest) (*UserMain, error)
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Activate(context.Context, *ActivateRequest) (*ActivateResponse, error)
}

// UnimplementedUsersServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServer struct {
}

func (*UnimplementedUsersServer) Add(ctx context.Context, req *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedUsersServer) Get(ctx context.Context, req *GetRequest) (*UserMain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedUsersServer) Auth(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedUsersServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedUsersServer) Activate(ctx context.Context, req *ActivateRequest) (*ActivateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Activate not implemented")
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Activate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Activate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/Activate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Activate(ctx, req.(*ActivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Users_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Users_Get_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _Users_Auth_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Users_Update_Handler,
		},
		{
			MethodName: "Activate",
			Handler:    _Users_Activate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-srv.proto",
}
