// Code generated by protoc-gen-go. DO NOT EDIT.
// source: verification-srv.proto

package verification_srv

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserData struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff5f3cc10b8d8345, []int{0}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type TokenData struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenData) Reset()         { *m = TokenData{} }
func (m *TokenData) String() string { return proto.CompactTextString(m) }
func (*TokenData) ProtoMessage()    {}
func (*TokenData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff5f3cc10b8d8345, []int{1}
}

func (m *TokenData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenData.Unmarshal(m, b)
}
func (m *TokenData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenData.Marshal(b, m, deterministic)
}
func (m *TokenData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenData.Merge(m, src)
}
func (m *TokenData) XXX_Size() int {
	return xxx_messageInfo_TokenData.Size(m)
}
func (m *TokenData) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenData.DiscardUnknown(m)
}

var xxx_messageInfo_TokenData proto.InternalMessageInfo

func (m *TokenData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Valid struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Valid) Reset()         { *m = Valid{} }
func (m *Valid) String() string { return proto.CompactTextString(m) }
func (*Valid) ProtoMessage()    {}
func (*Valid) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff5f3cc10b8d8345, []int{2}
}

func (m *Valid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Valid.Unmarshal(m, b)
}
func (m *Valid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Valid.Marshal(b, m, deterministic)
}
func (m *Valid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Valid.Merge(m, src)
}
func (m *Valid) XXX_Size() int {
	return xxx_messageInfo_Valid.Size(m)
}
func (m *Valid) XXX_DiscardUnknown() {
	xxx_messageInfo_Valid.DiscardUnknown(m)
}

var xxx_messageInfo_Valid proto.InternalMessageInfo

func (m *Valid) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Valid) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*UserData)(nil), "UserData")
	proto.RegisterType((*TokenData)(nil), "tokenData")
	proto.RegisterType((*Valid)(nil), "Valid")
}

func init() { proto.RegisterFile("verification-srv.proto", fileDescriptor_ff5f3cc10b8d8345) }

var fileDescriptor_ff5f3cc10b8d8345 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x4b, 0x2d, 0xca,
	0x4c, 0xcb, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2d, 0x2e, 0x2a, 0xd3, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x57, 0x52, 0xe2, 0xe2, 0x08, 0x2d, 0x4e, 0x2d, 0x72, 0x49, 0x2c, 0x49, 0x14, 0x12,
	0xe3, 0x62, 0x2b, 0x2d, 0x4e, 0x2d, 0xf2, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82,
	0xf2, 0x94, 0x14, 0xb9, 0x38, 0x4b, 0xf2, 0xb3, 0x53, 0xf3, 0xc0, 0x8a, 0x44, 0xb8, 0x58, 0xc1,
	0x1c, 0xa8, 0x1a, 0x08, 0x47, 0xc9, 0x94, 0x8b, 0x35, 0x2c, 0x31, 0x27, 0x33, 0x05, 0x97, 0x19,
	0x20, 0x6d, 0x65, 0x20, 0x05, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x10, 0x8e, 0x51, 0x38,
	0x97, 0x40, 0x18, 0x92, 0xbb, 0x9c, 0xf3, 0x53, 0x52, 0x85, 0x14, 0xb9, 0xd8, 0x9c, 0x8b, 0x52,
	0x13, 0x4b, 0x52, 0x85, 0x38, 0xf5, 0x60, 0x4e, 0x93, 0xe2, 0xd2, 0x83, 0xbb, 0x40, 0x89, 0x41,
	0x48, 0x81, 0x8b, 0x03, 0x6c, 0x1b, 0x48, 0x11, 0x92, 0x8c, 0x14, 0x9b, 0x1e, 0x58, 0x58, 0x89,
	0x21, 0x89, 0x0d, 0xec, 0x3b, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x56, 0x72, 0x0d, 0x62,
	0xf7, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VerificationCodeClient is the client API for VerificationCode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VerificationCodeClient interface {
	Create(ctx context.Context, in *UserData, opts ...grpc.CallOption) (*TokenData, error)
	Validate(ctx context.Context, in *TokenData, opts ...grpc.CallOption) (*Valid, error)
}

type verificationCodeClient struct {
	cc *grpc.ClientConn
}

func NewVerificationCodeClient(cc *grpc.ClientConn) VerificationCodeClient {
	return &verificationCodeClient{cc}
}

func (c *verificationCodeClient) Create(ctx context.Context, in *UserData, opts ...grpc.CallOption) (*TokenData, error) {
	out := new(TokenData)
	err := c.cc.Invoke(ctx, "/VerificationCode/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verificationCodeClient) Validate(ctx context.Context, in *TokenData, opts ...grpc.CallOption) (*Valid, error) {
	out := new(Valid)
	err := c.cc.Invoke(ctx, "/VerificationCode/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerificationCodeServer is the server API for VerificationCode service.
type VerificationCodeServer interface {
	Create(context.Context, *UserData) (*TokenData, error)
	Validate(context.Context, *TokenData) (*Valid, error)
}

// UnimplementedVerificationCodeServer can be embedded to have forward compatible implementations.
type UnimplementedVerificationCodeServer struct {
}

func (*UnimplementedVerificationCodeServer) Create(ctx context.Context, req *UserData) (*TokenData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedVerificationCodeServer) Validate(ctx context.Context, req *TokenData) (*Valid, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}

func RegisterVerificationCodeServer(s *grpc.Server, srv VerificationCodeServer) {
	s.RegisterService(&_VerificationCode_serviceDesc, srv)
}

func _VerificationCode_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationCodeServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VerificationCode/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationCodeServer).Create(ctx, req.(*UserData))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerificationCode_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationCodeServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VerificationCode/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationCodeServer).Validate(ctx, req.(*TokenData))
	}
	return interceptor(ctx, in, info, handler)
}

var _VerificationCode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "VerificationCode",
	HandlerType: (*VerificationCodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _VerificationCode_Create_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _VerificationCode_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verification-srv.proto",
}
