// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-extra-srv.proto

package user_extra_srv

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Gender               string   `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	BirthdayUTC          int64    `protobuf:"varint,5,opt,name=birthdayUTC,proto3" json:"birthdayUTC,omitempty"`
	Message              string   `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4fd40ec22cd6d3, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Data) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Data) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Data) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Data) GetBirthdayUTC() int64 {
	if m != nil {
		return m.BirthdayUTC
	}
	return 0
}

func (m *Data) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4fd40ec22cd6d3, []int{1}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4fd40ec22cd6d3, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type UpdateRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Update               *Data    `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4fd40ec22cd6d3, []int{3}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateRequest) GetUpdate() *Data {
	if m != nil {
		return m.Update
	}
	return nil
}

type UpdateResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4fd40ec22cd6d3, []int{4}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Data)(nil), "Data")
	proto.RegisterType((*AddResponse)(nil), "AddResponse")
	proto.RegisterType((*GetRequest)(nil), "GetRequest")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
}

func init() { proto.RegisterFile("user-extra-srv.proto", fileDescriptor_8e4fd40ec22cd6d3) }

var fileDescriptor_8e4fd40ec22cd6d3 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x1b, 0xd3, 0x46, 0x3b, 0xd1, 0x0a, 0x83, 0xc8, 0x12, 0x2b, 0x84, 0x45, 0xb0, 0x28,
	0xdd, 0x43, 0x7d, 0x82, 0x62, 0xb5, 0x78, 0xf1, 0x10, 0xcc, 0x03, 0x6c, 0xd9, 0xb1, 0x16, 0x6c,
	0x13, 0x77, 0x37, 0xa2, 0xef, 0xe4, 0x43, 0x4a, 0x36, 0xa9, 0x4d, 0x0e, 0xd2, 0xe3, 0x3f, 0xf3,
	0xed, 0xbf, 0xf3, 0xcf, 0xc0, 0x59, 0x61, 0x48, 0x8f, 0xe9, 0xcb, 0x6a, 0x39, 0x36, 0xfa, 0x53,
	0xe4, 0x3a, 0xb3, 0x19, 0xff, 0xf1, 0xa0, 0x3b, 0x93, 0x56, 0xe2, 0x39, 0x04, 0x25, 0xf0, 0x34,
	0x63, 0x5e, 0xec, 0x8d, 0xfa, 0x49, 0xad, 0x70, 0x08, 0xfd, 0xd7, 0x95, 0x36, 0xf6, 0x59, 0xae,
	0x89, 0x1d, 0xb8, 0xd6, 0xae, 0x80, 0x11, 0x1c, 0xbd, 0xcb, 0xba, 0xe9, 0xbb, 0xe6, 0x9f, 0x2e,
	0x1d, 0x97, 0xb4, 0x51, 0xa4, 0x59, 0xb7, 0x72, 0xac, 0x14, 0xc6, 0x10, 0x2e, 0x56, 0xda, 0xbe,
	0x29, 0xf9, 0x9d, 0xbe, 0xdc, 0xb3, 0x5e, 0xec, 0x8d, 0xfc, 0xa4, 0x59, 0x42, 0x06, 0x87, 0x6b,
	0x32, 0x46, 0x2e, 0x89, 0x05, 0xee, 0xe9, 0x56, 0xf2, 0x6b, 0x08, 0xa7, 0x4a, 0x25, 0x64, 0xf2,
	0x6c, 0x63, 0xa8, 0x09, 0x7a, 0x6d, 0xf0, 0x0a, 0x60, 0x4e, 0x36, 0xa1, 0x8f, 0x82, 0x8c, 0xfd,
	0x2f, 0x1c, 0x7f, 0x84, 0x93, 0x34, 0x57, 0xd2, 0xd2, 0x1e, 0x10, 0x2f, 0x21, 0x28, 0x1c, 0xe8,
	0x56, 0x10, 0x4e, 0x7a, 0xa2, 0x5c, 0x5a, 0x52, 0x17, 0xf9, 0x0d, 0x0c, 0xb6, 0x3e, 0xfb, 0x26,
	0x9b, 0x18, 0xe8, 0xa7, 0x86, 0xf4, 0x43, 0x79, 0x08, 0x1c, 0x82, 0x3f, 0x55, 0x0a, 0x2b, 0xbb,
	0xe8, 0x58, 0x34, 0xc2, 0xf1, 0x0e, 0x5e, 0x80, 0x3f, 0x27, 0x8b, 0xa1, 0xd8, 0x45, 0x89, 0x2a,
	0x94, 0x77, 0xf0, 0x16, 0x82, 0xea, 0x4f, 0x1c, 0x88, 0x56, 0x88, 0xe8, 0x54, 0xb4, 0x87, 0xe1,
	0x9d, 0x45, 0xe0, 0xae, 0x7d, 0xf7, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x1b, 0x45, 0xbd, 0x05,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserExtraClient is the client API for UserExtra service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserExtraClient interface {
	Add(ctx context.Context, in *Data, opts ...grpc.CallOption) (*AddResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Data, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type userExtraClient struct {
	cc *grpc.ClientConn
}

func NewUserExtraClient(cc *grpc.ClientConn) UserExtraClient {
	return &userExtraClient{cc}
}

func (c *userExtraClient) Add(ctx context.Context, in *Data, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/UserExtra/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userExtraClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Data, error) {
	out := new(Data)
	err := c.cc.Invoke(ctx, "/UserExtra/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userExtraClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/UserExtra/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserExtraServer is the server API for UserExtra service.
type UserExtraServer interface {
	Add(context.Context, *Data) (*AddResponse, error)
	Get(context.Context, *GetRequest) (*Data, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
}

// UnimplementedUserExtraServer can be embedded to have forward compatible implementations.
type UnimplementedUserExtraServer struct {
}

func (*UnimplementedUserExtraServer) Add(ctx context.Context, req *Data) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedUserExtraServer) Get(ctx context.Context, req *GetRequest) (*Data, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedUserExtraServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterUserExtraServer(s *grpc.Server, srv UserExtraServer) {
	s.RegisterService(&_UserExtra_serviceDesc, srv)
}

func _UserExtra_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserExtraServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserExtra/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserExtraServer).Add(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserExtra_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserExtraServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserExtra/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserExtraServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserExtra_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserExtraServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserExtra/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserExtraServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserExtra_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserExtra",
	HandlerType: (*UserExtraServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _UserExtra_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _UserExtra_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserExtra_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-extra-srv.proto",
}
